### ISSUE TITLE
Simply doesn't work

### ISSUE THREAD

**Issue by NinjaPancake** [swisspol/MP3CDMaker#8]
Aside from taking forever to recognise the library.

It also says all songs failed to convert on all of my playlists.

Really disappointing, especially after paying the $12.99 for unlimited songs option.

**Comment by swisspol** [comment]
Very sorry about that, did you try the app before purchasing? Was it working at the time?

What OS X and iTunes versions do you have?

**Comment by NinjaPancake** [comment]
10.10.2 and 12.1.0.50

I didn't, no. But in hindsight I should have. I bought it because I wanted to convert lists with more than 50 songs.

**Comment by swisspol** [comment]
What type of audio files are you trying to burn? MP3s? AACs? Protected AACs (i.e. with DRMs)?

What is the language used for your installation of OS X? Is it English?

Could you also launch the Console app from `/Applications/Utilities` and then select "All messages" on the left pane and search for "MP3" and copy-paste whatever you can find? It would really help understanding what is going on. Thanks.

**Comment by swisspol** [comment]
The price is also USD $9.99, not $12.99. In which App Store country did you buy it?

**Comment by NinjaPancake** [comment]
It's the Australian app store, so it's $12.99.

I'm trying to convert non DRM AAC to MP3. The language is English.

Here are the messages:

27/02/2015 3:12:35.527 pm storeaccountd[310]: ADI: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-transform, max-age=60";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 10046;
    "Content-Type" = "text/html; charset=UTF-8";
    Date = "Fri, 27 Feb 2015 05:12:35 GMT";
    "Last-Modified" = "Fri, 27 Feb 2015 05:12:35 GMT";
    Server = "ATS/4.1.0";
    "Strict-Transport-Security" = "max-age=31536000";
    Vary = "Accept-Encoding";
    "X-Apple-ATS-Cache-Key" = "/17.154.42.215/80/au/app/mp3-cd-maker/id820390388/iDevice/143460/13/https?mt=12";
    "X-Apple-Partner" = "origin.0";
    "apple-timing-app" = "49 ms";
    "x-apple-aka-ttl" = "Generated Thu Feb 26 21:12:35 PST 2015, Expires Thu Feb 26 21:13:35 PST 2015, TTL 60s";
    "x-apple-application-instance" = 1004801;
    "x-apple-application-site" = NWK;
    "x-apple-jingle-correlation-key" = EGZHQD32II3KLZEKTQNPD2PMFA;
    "x-apple-orig-url" = "https://itunes.apple.com/au/app/mp3-cd-maker/id820390388?mt=12&ign-msr=https%3A%2F%2Fwww.google.com.au%2F";
    "x-apple-translated-wo-url" = "/WebObjects/MZStore.woa/wa/viewSoftware?mt=12&ign-msr=https%3A%2F%2Fwww.google.com.au%2F&id=820390388&cc=au&urlDesc=/mp3-cd-maker";
    "x-frame-options" = SAMEORIGIN;
    "x-webobjects-loadaverage" = 0;
}
27/02/2015 3:13:04.294 pm com.apple.CommerceKit.TransactionService[686]: addOperation <ISStoreURLOperation: 0x7fe46b81c040 - request=<ISURLRequest:0x7fe46b89d350 https://securemetrics.apple.com/b/ss/applesuperglobal/1/G.6--NS?cc=AUD&pccr=true&c22=XML&products=F1%3B820390388%3B1%3B0.00000&ch=Purchase&c15=Software-AU-Pol-Online-MP3%20CD%20Maker-820390388&c16=Software%20Pages&cl=15778463&h5=appleitmswwwap%2Cappleitmsasap&v15=Software-AU-Pol-Online-MP3%20CD%20Maker-820390388&v22=XML&events=purchase&pageName=Buy&v16=Software%20Pages&purchaseID=76008209898255> urlBagKey=(null)>
27/02/2015 3:14:00.811 pm sandboxd[297]: ([310]) storeaccountd(310) deny file-write-data /Users/daniellato/Library/Preferences/net.pol-online.mp3-cd-maker.plist
27/02/2015 3:14:00.832 pm sandboxd[297]: ([310]) storeaccountd(310) deny file-write-data /Users/daniellato/Library/Preferences/net.pol-online.mp3-cd-maker.plist
27/02/2015 3:16:20.275 pm storeaccountd[310]: ADI: {
    "Cache-Control" = "no-transform, max-age=60";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 591;
    "Content-Type" = "text/xml; charset=UTF-8";
    Date = "Fri, 27 Feb 2015 05:16:20 GMT";
    "Last-Modified" = "Fri, 27 Feb 2015 05:16:20 GMT";
    Server = "ATS/4.1.0";
    "Strict-Transport-Security" = "max-age=31536000";
    Vary = "Accept-Encoding, X-Apple-Store-Front";
    "X-Apple-ATS-Cache-Key" = "/17.154.42.215/80/WebObjects/MZStore.woa/wa/fetchSoftwareAddOns/iDevice/143460/13/https?appAdamId=820390388&appExtVrsId=601183518&bid=net.pol-online.mp3-cd-maker&bvrs=1.0.1&icuLocale=en_AU&offerNames=mp3_cd_maker_unlimited";
    "X-Apple-Partner" = "origin.0";
    "apple-timing-app" = "5 ms";
    "x-apple-aka-ttl" = "Generated Thu Feb 26 21:16:20 PST 2015, Expires Thu Feb 26 21:17:20 PST 2015, TTL 60s";
    "x-apple-application-instance" = 1000104;
    "x-apple-application-site" = NWK;
    "x-apple-jingle-correlation-key" = ZPZ7CX6RCZL4NOYQ2EIIPNH74Q;
    "x-apple-orig-url" = "https://itunes.apple.com/WebObjects/MZStore.woa/wa/fetchSoftwareAddOns?appAdamId=820390388&bid=net.pol-online.mp3-cd-maker&icuLocale=en_AU&bvrs=1.0.1&appExtVrsId=601183518&offerNames=mp3_cd_maker_unlimited";
    "x-apple-translated-wo-url" = "/WebObjects/MZStore.woa/wa/fetchSoftwareAddOns?appAdamId=820390388&bid=net.pol-online.mp3-cd-maker&icuLocale=en_AU&bvrs=1.0.1&appExtVrsId=601183518&offerNames=mp3_cd_maker_unlimited";
    "x-frame-options" = SAMEORIGIN;
    "x-webobjects-loadaverage" = 0;
}
27/02/2015 3:17:08.388 pm sandboxd[297]: ([729]) MP3 CD Maker(729) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:17:08.408 pm sandboxd[297]: ([729]) MP3 CD Maker(729) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:17:25.074 pm sandboxd[297]: ([729]) MP3 CD Maker(729) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:17:25.080 pm sandboxd[297]: ([729]) MP3 CD Maker(729) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:18:11.826 pm sandboxd[297]: ([729]) MP3 CD Maker(729) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:18:11.832 pm sandboxd[297]: ([729]) MP3 CD Maker(729) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:18:41.072 pm sandboxd[297]: ([729]) MP3 CD Maker(729) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:18:41.078 pm sandboxd[297]: ([729]) MP3 CD Maker(729) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:27:15.000 pm kernel[0]: Sandbox: MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:27:15.000 pm kernel[0]: Sandbox: MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:27:15.000 pm kernel[0]: Sandbox: storeaccountd(314) deny file-write-data /Users/daniellato/Library/Preferences/net.pol-online.mp3-cd-maker.plist
27/02/2015 3:27:15.000 pm kernel[0]: Sandbox: storeaccountd(314) deny file-write-data /Users/daniellato/Library/Preferences/net.pol-online.mp3-cd-maker.plist
27/02/2015 3:27:35.000 pm kernel[0]: Sandbox: MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:27:35.000 pm kernel[0]: Sandbox: MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:27:58.000 pm kernel[0]: Sandbox: MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:27:58.000 pm kernel[0]: Sandbox: MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:28:37.109 pm sandboxd[308]: ([366]) MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:28:37.115 pm sandboxd[308]: ([366]) MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:28:41.881 pm sandboxd[308]: ([366]) MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:28:41.886 pm sandboxd[308]: ([366]) MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:28:46.344 pm sandboxd[308]: ([366]) MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:28:46.349 pm sandboxd[308]: ([366]) MP3 CD Maker(366) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:29:07.281 pm sandboxd[308]: ([408]) MP3 CD Maker(408) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:29:07.287 pm sandboxd[308]: ([408]) MP3 CD Maker(408) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:29:22.000 pm kernel[0]: Sandbox: MP3 CD Maker(408) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:29:22.000 pm kernel[0]: Sandbox: MP3 CD Maker(408) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:34:39.260 pm App Store[445]: addOperation <ISStoreURLOperation: 0x7f90baf1fb50 - request=<ISURLRequest:0x61000009d330 https://search.itunes.apple.com/WebObjects/MZSearchHints.woa/wa/hints?q=mp3> urlBagKey=(null)>
27/02/2015 3:34:39.660 pm App Store[445]: addOperation <ISStoreURLOperation: 0x7f90baf1fb50 - request=<ISURLRequest:0x61000009fd60 https://search.itunes.apple.com/WebObjects/MZSearchHints.woa/wa/hints?q=mp3%20> urlBagKey=(null)>
27/02/2015 3:34:39.872 pm App Store[445]: addOperation <ISStoreURLOperation: 0x7f90bae1fb90 - request=<ISURLRequest:0x600000282030 https://search.itunes.apple.com/WebObjects/MZSearchHints.woa/wa/hints?q=mp3%20c> urlBagKey=(null)>
27/02/2015 3:34:40.060 pm App Store[445]: addOperation <ISStoreURLOperation: 0x7f90bad31180 - request=<ISURLRequest:0x61800009dba0 https://search.itunes.apple.com/WebObjects/MZSearchHints.woa/wa/hints?q=mp3%20cd> urlBagKey=(null)>
27/02/2015 3:34:45.720 pm storeaccountd[314]: ADI: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-transform, max-age=60";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 10053;
    "Content-Type" = "text/html; charset=UTF-8";
    Date = "Fri, 27 Feb 2015 05:34:45 GMT";
    "Last-Modified" = "Fri, 27 Feb 2015 05:34:45 GMT";
    Server = "ATS/4.1.0";
    "Strict-Transport-Security" = "max-age=31536000";
    Vary = "Accept-Encoding";
    "X-Apple-ATS-Cache-Key" = "/17.173.38.162/80/au/app/mp3-cd-maker/id820390388/iDevice/143460/13/https?mt=12";
    "X-Apple-Partner" = "origin.0";
    "apple-timing-app" = "39 ms";
    "x-apple-aka-ttl" = "Generated Thu Feb 26 21:34:45 PST 2015, Expires Thu Feb 26 21:35:45 PST 2015, TTL 60s";
    "x-apple-application-instance" = 2126145;
    "x-apple-application-site" = ST11;
    "x-apple-jingle-correlation-key" = 5M6HFVBVHGKOFSE7TXRMMFVXVQ;
    "x-apple-orig-url" = "https://itunes.apple.com/au/app/mp3-cd-maker/id820390388?mt=12";
    "x-apple-translated-wo-url" = "/WebObjects/MZStore.woa/wa/viewSoftware?mt=12&id=820390388&cc=au&urlDesc=/mp3-cd-maker";
    "x-frame-options" = SAMEORIGIN;
    "x-webobjects-loadaverage" = 0;
}
27/02/2015 3:37:40.792 pm sandboxd[308]: ([461]) MP3 CD Maker(461) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:37:40.798 pm sandboxd[308]: ([461]) MP3 CD Maker(461) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:37:59.530 pm sandboxd[308]: ([461]) MP3 CD Maker(461) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:37:59.536 pm sandboxd[308]: ([461]) MP3 CD Maker(461) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:46:31.032 pm sandboxd[308]: ([484]) MP3 CD Maker(484) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:46:31.038 pm sandboxd[308]: ([484]) MP3 CD Maker(484) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:46:41.363 pm sandboxd[308]: ([484]) MP3 CD Maker(484) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library
27/02/2015 3:46:41.369 pm sandboxd[308]: ([484]) MP3 CD Maker(484) deny file-read-data /Volumes/Macintosh HD 2/iTunes Music Library

**Comment by swisspol** [comment]
Looks like a Sandboxing issue (https://www.apple.com/osx/what-is/security/).... OS X doesn't allow the app to access the iTunes library on your computer :( It's a security "feature" so there's not much the app can do on its side.

One possible factor though is that it also looks like your iTunes library is not on the startup disk, is this correct?

The "iTunes Library", which contains all the iTunes metadata, is typically located at `/Users/{YOUR_USERNAME}/Music/iTunes` and the "iTunes Media folder", which contains all the actual music files, is typically located at `/Users/{YOUR_USERNAME}/Music/iTunes/iTunes Media/Music`. However people can freely move one or both elsewhere. Can you let me know where the "iTunes Library" and "iTunes Media folder" are in your case?

**Comment by NinjaPancake** [comment]
Ah. Got it!

So the library XML is on my main HD, but the music files are on my HD 2. Selecting the library on my main drive has allowed me to access the files on the HD 2.

Phew! Thank you for getting back to me, I'm really glad we could sort this out!

**Comment by swisspol** [comment]
Awesome!
